name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: checkboxes
    id: not-a-fork
    attributes:
      label: Official version
      description: We only provide support for the official octo-fiesta repository, not forks.
      options:
        - label: I confirm I'm using the official octo-fiesta, not a fork
          required: true

  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please describe your idea clearly so we can understand what you're looking for.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this relate to?
      options:
        - Subsonic API
        - Deezer provider
        - Qobuz provider
        - SquidWTF provider
        - Local library
        - Playlists
        - Docker / Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or examples that might help.
